
services:
  firestore-emulator:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    container_name: firestore_emulator
    ports:
      - "8080:8080"
    command: gcloud beta emulators firestore start --host-port=0.0.0.0:8080

  pubsub-emulator:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    container_name: pubsub_emulator
    ports:
      - "8085:8085"
    command: gcloud beta emulators pubsub start --host-port=0.0.0.0:8085
