spring.application.name=api_service

# Run Spring Boot on port 8081 so it doesn't conflict with Firestore emulator
server.port=8081

# Google Cloud Project ID
spring.cloud.gcp.project-id=fintech-hackathon

# Firestore Emulator Config
spring.cloud.gcp.firestore.emulator.enabled=true
spring.cloud.gcp.firestore.host-port=127.0.0.1:8080

# Pub/Sub Emulator Config
spring.cloud.gcp.pubsub.emulator-host=127.0.0.1:8085
